### ISSUE TITLE
[FIXED] Bug Report: Missing phone number validation

### ISSUE THREAD

**Issue by katsoohoo** [katsoohoo/CS160ButtGroup4#43]
User can enter a very long digit number. Phone number section missing input validation.

**Comment by ProngeM** [comment]
I'll work on this, I'll also take the time to go over all the forms for registration, to see if any of the other input validation needs strengthening.

**Comment by ProngeM** [comment]
so I have corrected this problem on my end. I had to edit each form to include the code "maxlength = "10"", so that way they should not be making arbitrarily large phone numbers.
 In addition to that, I found a way to set a minimum length for phone numbers. It basically involved adding an additional check to the phone section of each input validation page. If it is ok with you guys, I am going to apply that to minimum length check to each phone number, and wherever else in the input validation deemed appropriate. looking at each page though, I think the only other field that this should apply to is the year of a car, that way they can't make a 20000 honda civic or a 900 chevy volt

**Comment by ProngeM** [comment]
I have gone and added all of the input validation to each page. I modified profile-driver.php, profile-rider.php,  profileUpdateDriver.php,  profileUpdateRider.php, registerValidateDriver.php, and registerValidateRider.php . each one now has a much more comprehensive set of checks for phone numbers. I also added similar checks for a car's year. I did find another pretty big bug with updating a driver's car though, when you go to submit the update car form on the driver profile page, an sql error message pops up. I am not sure what the problem is however. it seems that this is an existing bug, because i found the error in the outdated master branch, and it was still there in the post-bug-report branch.
